import { Book } from '../entities/book.entity';

export const BookData: Book[] = [
  new Book({
    id: 1,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Classic',
    publishedYear: 1925,
    description:
      'A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan',
    price: 12.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 2,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Classic',
    publishedYear: 1960,
    description:
      'The story of young Scout Finch and her father Atticus in a racially divided Alabama town',
    price: 14.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 3,
    title: '1984',
    author: 'George Orwell',
    genre: 'Dystopian',
    publishedYear: 1949,
    description:
      'A dystopian novel about totalitarianism and surveillance society',
    price: 11.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 4,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Romance',
    publishedYear: 1813,
    description:
      'The story of Elizabeth Bennet and her relationship with the proud Mr. Darcy',
    price: 9.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 5,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    publishedYear: 1937,
    description:
      'Bilbo Baggins embarks on an adventure with thirteen dwarves to reclaim their homeland',
    price: 16.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 6,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Coming-of-age',
    publishedYear: 1951,
    description:
      "Holden Caulfield's journey through New York City and his struggle with adolescence",
    price: 13.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 7,
    title: 'Lord of the Flies',
    author: 'William Golding',
    genre: 'Allegory',
    publishedYear: 1954,
    description: 'A group of boys stranded on an island descend into savagery',
    price: 10.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 8,
    title: 'Animal Farm',
    author: 'George Orwell',
    genre: 'Satire',
    publishedYear: 1945,
    description:
      'A satirical allegory of the Russian Revolution through the lens of farm animals',
    price: 8.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 9,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    publishedYear: 1954,
    description:
      "Frodo Baggins' epic quest to destroy the One Ring and save Middle-earth",
    price: 24.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  new Book({
    id: 10,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    genre: 'Dystopian',
    publishedYear: 1932,
    description:
      'A dystopian novel about a futuristic society controlled by technology and conditioning',
    price: 12.99,
    isAvailable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
];
